spring:
  application:
    name: lecture-spring-ai
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      resolve-lazily: true
  datasource:
    url: jdbc:postgresql://192.168.2.100:5433/springai
    username: Administrator
    password: Libin704098.00
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384  # 之所以将维度定为384，是因为之前选的向量转化模型（all-minilm）支持的维度就是384
        batching-strategy: TOKEN_COUNT
        max-document-batch-size: 10000
    ollama:
      base-url: http://192.168.2.100:11434
      chat:
        options:
          model: deepseek-r1:1.5b
      embedding:
        enabled: true
        model: all-minilm
        # model: mistral
    moonshot:
      api-key: ${MOONSHOT_API_KEY}
      chat:
        options:
          model: moonshot-v1-8k
          temperature: 0.7

server:
  servlet:
    encoding:
      charset: UTF-8

# 配置日志
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG
